const PHONE_HOME_LIST_SHEET = "16shCHnP8TrRm9IpohGnpmgBiIXX6-IJFAQVdOMTaTZ8"
const PHONE_HOME_LIST_TAB = "List"
const PHONE_HOME_LIST_HEADER_INDEX = 0


const CASE_ID_SEARCH_SHEET_1 = "1E7rirLBJj2Sy_0KrWDpWZVnYfJoPHka014oAuc2GDwg"

const CASE_SEARCH_1_IN_HOSPITAL_SHEET = CASE_ID_SEARCH_SHEET_1
const CASE_SEARCH_1_IN_HOSPITAL_TAB = "in hospital"
const CASE_SEARCH_1_IN_HOSPITAL_HEADER_INDEX = 1

const CASE_SEARCH_1_PHONE_HOME_SHEET = CASE_ID_SEARCH_SHEET_1
const CASE_SEARCH_1_PHONE_HOME_TAB = "out of hospital"
const CASE_SEARCH_1_PHONE_HOME_HEADER_INDEX = 1

const CASE_SEARCH_1_ADDRESS_SHEET = CASE_ID_SEARCH_SHEET_1
const CASE_SEARCH_1_ADDRESS_TAB = "address"
const CASE_SEARCH_1_ADDRESS_HEADER_INDEX = 1


const CASE_ID_SEARCH_SHEET_2 = "1bCTjmoqaWcmSorN-45T6uRF1WgdhmeGO6vNIQ5l504M"

const CASE_SEARCH_2_IN_HOSPITAL_SHEET = CASE_ID_SEARCH_SHEET_2
const CASE_SEARCH_2_IN_HOSPITAL_TAB = "in hospital"
const CASE_SEARCH_2_IN_HOSPITAL_HEADER_INDEX = 1

const CASE_SEARCH_2_PHONE_HOME_SHEET = CASE_ID_SEARCH_SHEET_2
const CASE_SEARCH_2_PHONE_HOME_TAB = "out of hospital"
const CASE_SEARCH_2_PHONE_HOME_HEADER_INDEX = 1

const CASE_SEARCH_2_ADDRESS_SHEET = CASE_ID_SEARCH_SHEET_2
const CASE_SEARCH_2_ADDRESS_TAB = "address"
const CASE_SEARCH_2_ADDRESS_HEADER_INDEX = 1


const CASE_ID_SEARCH_SHEET_3 = "1c2NVK-x2_hL7tnOe3uIhnBr0oov4dfaNnLpVh9Gy00o"

const CASE_SEARCH_3_IN_HOSPITAL_SHEET = CASE_ID_SEARCH_SHEET_3
const CASE_SEARCH_3_IN_HOSPITAL_TAB = "in hospital"
const CASE_SEARCH_3_IN_HOSPITAL_HEADER_INDEX = 1

const CASE_SEARCH_3_PHONE_HOME_SHEET = CASE_ID_SEARCH_SHEET_3
const CASE_SEARCH_3_PHONE_HOME_TAB = "out of hospital"
const CASE_SEARCH_3_PHONE_HOME_HEADER_INDEX = 1

const CASE_SEARCH_3_ADDRESS_SHEET = CASE_ID_SEARCH_SHEET_3
const CASE_SEARCH_3_ADDRESS_TAB = "address"
const CASE_SEARCH_3_ADDRESS_HEADER_INDEX = 1



const CASE_ID_SEARCH_SHEET_4 = "17MFmFfE308NdIoDvzTcYDq4KB0F1ZKq6_aFybA9k2YE"

const CASE_SEARCH_4_IN_HOSPITAL_SHEET = CASE_ID_SEARCH_SHEET_4
const CASE_SEARCH_4_IN_HOSPITAL_TAB = "in hospital"
const CASE_SEARCH_4_IN_HOSPITAL_HEADER_INDEX = 1

const CASE_SEARCH_4_PHONE_HOME_SHEET = CASE_ID_SEARCH_SHEET_4
const CASE_SEARCH_4_PHONE_HOME_TAB = "out of hospital"
const CASE_SEARCH_4_PHONE_HOME_HEADER_INDEX = 1

const CASE_SEARCH_4_ADDRESS_SHEET = CASE_ID_SEARCH_SHEET_4
const CASE_SEARCH_4_ADDRESS_TAB = "address"
const CASE_SEARCH_4_ADDRESS_HEADER_INDEX = 1



const CASE_ID_SEARCH_SHEET_5 = "1f9GozcU363mXRORb32PUG_jtF_COGtqxLgsZgZ0_6Z8"

const CASE_SEARCH_5_IN_HOSPITAL_SHEET = CASE_ID_SEARCH_SHEET_5
const CASE_SEARCH_5_IN_HOSPITAL_TAB = "in hospital"
const CASE_SEARCH_5_IN_HOSPITAL_HEADER_INDEX = 1

const CASE_SEARCH_5_PHONE_HOME_SHEET = CASE_ID_SEARCH_SHEET_5
const CASE_SEARCH_5_PHONE_HOME_TAB = "out of hospital"
const CASE_SEARCH_5_PHONE_HOME_HEADER_INDEX = 1

const CASE_SEARCH_5_ADDRESS_SHEET = CASE_ID_SEARCH_SHEET_5
const CASE_SEARCH_5_ADDRESS_TAB = "address"
const CASE_SEARCH_5_ADDRESS_HEADER_INDEX = 1




const CASE_ID_SEARCH_SHEET_6 = "1mTL041j5DU39xja0YdU1AKie73P2Mn1BFmpEnJEjdv8"

const CASE_SEARCH_6_IN_HOSPITAL_SHEET = CASE_ID_SEARCH_SHEET_6
const CASE_SEARCH_6_IN_HOSPITAL_TAB = "in hospital"
const CASE_SEARCH_6_IN_HOSPITAL_HEADER_INDEX = 1

const CASE_SEARCH_6_PHONE_HOME_SHEET = CASE_ID_SEARCH_SHEET_6
const CASE_SEARCH_6_PHONE_HOME_TAB = "out of hospital"
const CASE_SEARCH_6_PHONE_HOME_HEADER_INDEX = 1

const CASE_SEARCH_6_ADDRESS_SHEET = CASE_ID_SEARCH_SHEET_6
const CASE_SEARCH_6_ADDRESS_TAB = "address"
const CASE_SEARCH_6_ADDRESS_HEADER_INDEX = 1



const CASE_ID_SEARCH_SHEET_7 = "1MnaNwmZQGSkf_EIC9hQ-np2LV8nqpGsQ6qdgiGR2ZLo"

const CASE_SEARCH_7_IN_HOSPITAL_SHEET = CASE_ID_SEARCH_SHEET_7
const CASE_SEARCH_7_IN_HOSPITAL_TAB = "in hospital"
const CASE_SEARCH_7_IN_HOSPITAL_HEADER_INDEX = 1

const CASE_SEARCH_7_PHONE_HOME_SHEET = CASE_ID_SEARCH_SHEET_7
const CASE_SEARCH_7_PHONE_HOME_TAB = "out of hospital"
const CASE_SEARCH_7_PHONE_HOME_HEADER_INDEX = 1

const CASE_SEARCH_7_ADDRESS_SHEET = CASE_ID_SEARCH_SHEET_7
const CASE_SEARCH_7_ADDRESS_TAB = "address"
const CASE_SEARCH_7_ADDRESS_HEADER_INDEX = 1




const CASE_ID_SEARCH_SHEET_8 = "1HqiH6k8PjkYwrV-tQT9qrinUP023cUx9twpgoNpiT-E"

const CASE_SEARCH_8_IN_HOSPITAL_SHEET = CASE_ID_SEARCH_SHEET_8
const CASE_SEARCH_8_IN_HOSPITAL_TAB = "in hospital"
const CASE_SEARCH_8_IN_HOSPITAL_HEADER_INDEX = 1

const CASE_SEARCH_8_PHONE_HOME_SHEET = CASE_ID_SEARCH_SHEET_8
const CASE_SEARCH_8_PHONE_HOME_TAB = "out of hospital"
const CASE_SEARCH_8_PHONE_HOME_HEADER_INDEX = 1

const CASE_SEARCH_8_ADDRESS_SHEET = CASE_ID_SEARCH_SHEET_8
const CASE_SEARCH_8_ADDRESS_TAB = "address"
const CASE_SEARCH_8_ADDRESS_HEADER_INDEX = 1




const CASE_ID_SEARCH_SHEET_9 = "1Nebv2582jy3KtrqTVWO_2lT0HK7zrZXueHpXbyf5N5Y"

const CASE_SEARCH_9_IN_HOSPITAL_SHEET = CASE_ID_SEARCH_SHEET_9
const CASE_SEARCH_9_IN_HOSPITAL_TAB = "in hospital"
const CASE_SEARCH_9_IN_HOSPITAL_HEADER_INDEX = 1

const CASE_SEARCH_9_PHONE_HOME_SHEET = CASE_ID_SEARCH_SHEET_9
const CASE_SEARCH_9_PHONE_HOME_TAB = "out of hospital"
const CASE_SEARCH_9_PHONE_HOME_HEADER_INDEX = 1

const CASE_SEARCH_9_ADDRESS_SHEET = CASE_ID_SEARCH_SHEET_9
const CASE_SEARCH_9_ADDRESS_TAB = "address"
const CASE_SEARCH_9_ADDRESS_HEADER_INDEX = 1


const CASE_ID_SEARCH_SHEET_10 = "1rixviQF4npS6Bbk-cJceTZsua6zPMZFxQ6iRLEUvEX0"

const CASE_SEARCH_10_IN_HOSPITAL_SHEET = CASE_ID_SEARCH_SHEET_10
const CASE_SEARCH_10_IN_HOSPITAL_TAB = "in hospital"
const CASE_SEARCH_10_IN_HOSPITAL_HEADER_INDEX = 1

const CASE_SEARCH_10_PHONE_HOME_SHEET = CASE_ID_SEARCH_SHEET_10
const CASE_SEARCH_10_PHONE_HOME_TAB = "out of hospital"
const CASE_SEARCH_10_PHONE_HOME_HEADER_INDEX = 1

const CASE_SEARCH_10_ADDRESS_SHEET = CASE_ID_SEARCH_SHEET_10
const CASE_SEARCH_10_ADDRESS_TAB = "address"
const CASE_SEARCH_10_ADDRESS_HEADER_INDEX = 1



const CASE_ID_SEARCH_SHEET_11 = "1Uvwa9X5mjcy5y4heVOqBU5ESUBX-NqsMS5UTQ1YCMV4"

const CASE_SEARCH_11_IN_HOSPITAL_SHEET = CASE_ID_SEARCH_SHEET_11
const CASE_SEARCH_11_IN_HOSPITAL_TAB = "in hospital"
const CASE_SEARCH_11_IN_HOSPITAL_HEADER_INDEX = 1

const CASE_SEARCH_11_PHONE_HOME_SHEET = CASE_ID_SEARCH_SHEET_11
const CASE_SEARCH_11_PHONE_HOME_TAB = "out of hospital"
const CASE_SEARCH_11_PHONE_HOME_HEADER_INDEX = 1

const CASE_SEARCH_11_ADDRESS_SHEET = CASE_ID_SEARCH_SHEET_11
const CASE_SEARCH_11_ADDRESS_TAB = "address"
const CASE_SEARCH_11_ADDRESS_HEADER_INDEX = 1



const CASE_ID_SEARCH_SHEET_12 = "1Vm15i-o9e6DUD4q8yjUhHf3rvU-tRV1TFSZjJwiB6rU"

const CASE_SEARCH_12_IN_HOSPITAL_SHEET = CASE_ID_SEARCH_SHEET_12
const CASE_SEARCH_12_IN_HOSPITAL_TAB = "in hospital"
const CASE_SEARCH_12_IN_HOSPITAL_HEADER_INDEX = 1

const CASE_SEARCH_12_PHONE_HOME_SHEET = CASE_ID_SEARCH_SHEET_12
const CASE_SEARCH_12_PHONE_HOME_TAB = "out of hospital"
const CASE_SEARCH_12_PHONE_HOME_HEADER_INDEX = 1

const CASE_SEARCH_12_ADDRESS_SHEET = CASE_ID_SEARCH_SHEET_12
const CASE_SEARCH_12_ADDRESS_TAB = "address"
const CASE_SEARCH_12_ADDRESS_HEADER_INDEX = 1



const CASE_ID_SEARCH_SHEET_13 = "1mBtLQSrkwQIyTg1uwYFDgvVpnDAeF09b68jPKYjXibI"

const CASE_SEARCH_13_IN_HOSPITAL_SHEET = CASE_ID_SEARCH_SHEET_13
const CASE_SEARCH_13_IN_HOSPITAL_TAB = "in hospital"
const CASE_SEARCH_13_IN_HOSPITAL_HEADER_INDEX = 1

const CASE_SEARCH_13_PHONE_HOME_SHEET = CASE_ID_SEARCH_SHEET_13
const CASE_SEARCH_13_PHONE_HOME_TAB = "out of hospital"
const CASE_SEARCH_13_PHONE_HOME_HEADER_INDEX = 1

const CASE_SEARCH_13_ADDRESS_SHEET = CASE_ID_SEARCH_SHEET_13
const CASE_SEARCH_13_ADDRESS_TAB = "address"
const CASE_SEARCH_13_ADDRESS_HEADER_INDEX = 1



