const DATA_CHECKS_SHEET = "1YX_qHTx7rTTY5oLtrZaKfmH_nRF8GzVBt3duBaToNDA"

const PATIENT_FORM_SHEET = DATA_CHECKS_SHEET
const PATIENT_FORM_TAB = "patient location & forms"
const PATIENT_FORM_HEADER_INDEX = 0

const INTAKE_INFO_SHEET = DATA_CHECKS_SHEET
const INTAKE_INFO_TAB = "imp intake info"
const INTAKE_INFO_HEADER_INDEX = 0

const ERROR_CHECKS_SHEET = DATA_CHECKS_SHEET
const ERROR_CHECKS_TAB = "error check"
const ERROR_CHECKS_HEADER_INDEX = 0